import React from 'react';

interface VerificationDetailsProps {
  employeeVerified?: boolean;
  driverVerified?: boolean;
  vehicleVerified?: boolean;
  rideVerified?: boolean;
  timeValid?: boolean;
  locationPending?: boolean;
  verificationMethod?: string;
  verificationId?: string;
  timestamp?: string;
  employeeName?: string;
  employeeId?: string;
  driverName?: string;
  driverId?: string;
  vehiclePlate?: string;
  rideId?: string;
  onBack?: () => void;
  className?: string;
}

export const VerificationDetails: React.FC<VerificationDetailsProps> = ({
  employeeVerified = true,
  driverVerified = true,
  vehicleVerified = true,
  rideVerified = true,
  timeValid = true,
  locationPending = true,
  verificationMethod = 'Dynamic QR',
  verificationId = 'VRF-928172',
  timestamp = '07:31:22 AM',
  employeeName = 'Akshat Gupta',
  employeeId = 'EMP-10481',
  driverName = 'Raj Kumar',
  driverId = 'DRV-8492',
  vehiclePlate = 'MH12AB1234',
  rideId = 'RID-10421',
  onBack,
  className = '',
}) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const auditChecks = [
    { label: 'Employee', status: employeeVerified ? 'Verified' : 'Unverified', valid: employeeVerified, meta: `${employeeName} · ${employeeId}` },
    { label: 'Driver', status: driverVerified ? 'Verified' : 'Unverified', valid: driverVerified, meta: `${driverName} · ${driverId}` },
    { label: 'Vehicle', status: vehicleVerified ? 'Verified' : 'Unverified', valid: vehicleVerified, meta: `${vehiclePlate} · Toyota Innova` },
    { label: 'Ride', status: rideVerified ? 'Verified' : 'Unverified', valid: rideVerified, meta: `${rideId} · Morning Shift` },
    { label: 'Time', status: timeValid ? 'Valid' : 'Invalid Window', valid: timeValid, meta: 'Within ±15m schedule compliance' },
    { label: 'Location', status: locationPending ? 'Pending' : 'Verified', valid: !locationPending, isPending: locationPending, meta: 'Geofence proximity lock (Kothrud point)' },
  ];

  return (
    <div className={`p-4 flex flex-col justify-between min-h-full bg-slate-900 text-white ${className}`}>
      <div>
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-slate-800 mb-3">
          <button
            onClick={onBack}
            className="flex items-center gap-1 text-slate-400 hover:text-white text-xs font-semibold cursor-pointer"
          >
            <span>←</span>
            <span>Back</span>
          </button>
          <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-blue-500/20 border border-blue-400/40 text-blue-300 text-[9px] font-bold uppercase tracking-wider">
            <span className="w-1.5 h-1.5 rounded-full bg-blue-400"></span>
            SECURITY AUDIT LOG
          </div>
        </div>

        {/* Title */}
        <div className="mb-4">
          <div className="flex items-center gap-2 mb-1">
            <div className="w-6 h-6 rounded-lg bg-blue-600 flex items-center justify-center text-xs">
              🛡️
            </div>
            <h2 className="text-base font-black tracking-tight text-white uppercase">
              TRUSTPASS DETAILS
            </h2>
          </div>
          <p className="text-[10px] text-slate-400">
            Cryptographic audit trail generated by Shivneri Security Engine
          </p>
        </div>

        {/* Audit Verification List */}
        <div className="rounded-2xl bg-slate-800/80 border border-slate-700 p-3 mb-3 space-y-2">
          {auditChecks.map((item, idx) => (
            <div
              key={idx}
              className="flex items-center justify-between py-1.5 border-b border-slate-700/50 last:border-0 text-xs"
            >
              <div>
                <div className="font-semibold text-slate-200">{item.label}</div>
                <div className="text-[9px] text-slate-400 mono">{item.meta}</div>
              </div>
              <div className="text-right">
                {item.isPending ? (
                  <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-amber-400">
                    <span>○</span>
                    <span>Pending</span>
                  </span>
                ) : item.valid ? (
                  <span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-400">
                    <span>✓</span>
                    <span>{item.status}</span>
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1 text-[11px] font-bold text-red-400">
                    <span>✗</span>
                    <span>{item.status}</span>
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Technical Metadata Box */}
        <div className="rounded-2xl bg-slate-800/80 border border-slate-700 p-3 mb-3 space-y-2">
          <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">
            Handshake Metadata
          </div>

          <div className="flex items-center justify-between text-xs py-1 border-b border-slate-700/50">
            <span className="text-slate-400">Verification Method</span>
            <span className="font-semibold text-white bg-blue-600/30 border border-blue-500/40 px-2 py-0.5 rounded text-[10px]">
              {verificationMethod}
            </span>
          </div>

          <div className="flex items-center justify-between text-xs py-1 border-b border-slate-700/50">
            <span className="text-slate-400">Verification ID</span>
            <span className="mono font-bold text-emerald-400 text-xs">{verificationId}</span>
          </div>

          <div className="flex items-center justify-between text-xs py-1">
            <span className="text-slate-400">Timestamp</span>
            <span className="mono font-bold text-slate-200 text-xs">{timestamp}</span>
          </div>
        </div>

        {/* Cryptographic Digital Signature Card */}
        <div className="rounded-xl bg-slate-950/70 border border-slate-800 p-2.5 text-[9px] text-slate-400 space-y-1">
          <div className="flex items-center justify-between text-slate-500 font-mono">
            <span>HMAC-SHA256 DIGITAL HASH</span>
            <span className="text-emerald-500">VALID SIGNATURE</span>
          </div>
          <div className="mono text-[8px] text-slate-300 break-all bg-black/40 p-1.5 rounded border border-slate-800">
            e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
          </div>
          <div className="flex items-center justify-between pt-1">
            <span>Protocol: SHIVNERI-TP-v2.4</span>
            <span>Cipher: AES-GCM-256</span>
          </div>
        </div>
      </div>

      {/* Footer Buttons */}
      <div className="pt-3 space-y-2">
        <button
          onClick={handleCopy}
          className="w-full py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl border border-slate-600 flex items-center justify-center gap-1.5 cursor-pointer"
        >
          <span>📋</span>
          <span>{copied ? 'Audit ID Copied to Clipboard!' : 'Copy Verification Hash'}</span>
        </button>

        <button
          onClick={onBack}
          className="w-full py-2.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded-xl shadow-md cursor-pointer text-center"
        >
          Return to Ride
        </button>
      </div>
    </div>
  );
};

export default VerificationDetails;
